---
  dataSource: "milestones"
  prefix: "n"
  ignoreLabels: 
    - "devops"
    - "research"
  ignoreTagsWith: 
    - ""
  groupBy: "label"
  milestoneMatch: "Release {{tag_name}}"
  changelogFilename: "CHANGELOG.md"
