---
  #dataSource: "milestones" #milestones|issues|commits|prs
  dataSource: "issues"
  prefix: ""
  #ignoreLabels: ""
  ignoreIssuesWith: #actual meaning is: ignore issues 'labeled' with.
    - "devops"
    - "research"
  ignoreTagsWith: 
    - "interim"
    - "alpha"
    - "beta"
    #- "pre-release"
  groupBy: "label"
  #milestoneMatch: "Release {{tag_name}}"
  milestoneMatch: "v"
  changelogFilename: "published/CHANGELOG.md"
